ServerName: winthier
ServerDisplayName: Winthier
channels:
  global:
    tag: G
    title: Global
    aliases: [ global, g ]
    description: Cross server chat
  local:
    tag: L
    title: Local
    aliases: [ local, l ]
    description: Local chat with limited range
    range: 500
  pm:
    tag: PM
    title: Private
    aliases: [ pm, tell, msg, w ]
    description: Private messages
  party:
    tag: P
    title: Party
    aliases: [ p ]
    description: Party chat
  admin:
    tag: A
    title: Admin
    aliases: [ admin, a ]
    description: Admin chat
  moderator:
    tag: Mc
    title: Moderator
    aliases: [ mc ]
    description: Moderator chat
  trusted:
    tag: Tr
    title: Trusted
    aliases: [ tr, st ]
    description: Trusted chat
  information:
    tag: Info
    title: Info
    aliases: [ information, info ]
    description: General information
    range: -1
  mini:
    tag: Mini
    title: Mini
    aliases: [ mini ]
    description: Minigames broadcasting
    range: -1
settings:
- channel: global
  key: SenderColor
  value: gray
- channel: global
  key: BracketType
  value: brackets
- channel: global
  key: ChannelColor
  value: white
- channel: global
  key: PostToDynmap
  value: 1

- channel: local
  key: ChannelColor
  value: dark_aqua
- channel: local
  key: TextColor
  value: dark_aqua
- channel: local
  key: BracketType
  value: paren
- channel: local
  key: ShowServer
  value: 0

- channel: pm
  key: ChannelColor
  value: dark_purple
- channel: pm
  key: TextColor
  value: dark_purple
- channel: pm
  key: SenderColor
  value: dark_purple
- channel: pm
  key: BracketType
  value: angle

- channel: party
  key: ChannelColor
  value: blue
- channel: party
  key: TextColor
  value: blue
- channel: party
  key: BracketType
  value: paren
- channel: party
  key: ShowServer
  value: 0
- channel: party
  key: ShowChannelTag
  value: 1

- channel: admin
  key: ChannelColor
  value: aqua
- channel: admin
  key: BracketType
  value: curly
- channel: admin
  key: BracketColor
  value: aqua
- channel: admin
  key: SenderColor
  value: white
- channel: admin
  key: TextColor
  value: aqua
- channel: admin
  key: ShowChannelTag
  value: 0
- channel: admin
  key: ShowServer
  value: 0
- channel: admin
  key: ShowPlayerTitle
  value: 0
- channel: admin
  key: TagPlayerName
  value: 1

- channel: moderator
  key: ChannelColor
  value: red
- channel: moderator
  key: BracketType
  value: brackets
- channel: moderator
  key: BracketColor
  value: gray
- channel: moderator
  key: SenderColor
  value: red
- channel: moderator
  key: TextColor
  value: gray
- channel: moderator
  key: ShowChannelTag
  value: 0
- channel: moderator
  key: ShowServer
  value: 0
- channel: moderator
  key: ShowPlayerTitle
  value: 0

- channel: trusted
  key: ChannelColor
  value: blue
- channel: trusted
  key: BracketType
  value: brackets
- channel: trusted
  key: BracketColor
  value: gold
- channel: trusted
  key: SenderColor
  value: blue
- channel: trusted
  key: TextColor
  value: gold
- channel: trusted
  key: ShowChannelTag
  value: 0
- channel: trusted
  key: ShowServer
  value: 0
- channel: trusted
  key: ShowPlayerTitle
  value: 0

- channel: information
  key: ChannelColor
  value: dark_gray

- channel: mini
  key: ChannelColor
  value: gold

patterns:
  URL:
  - ['\b(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.-]*)*\/?\b', website]
  Spam:
  - ['!!+', '!']
  - ['\?\?+', '?']
  Language:
  - ['n[1i]gga|n[1i]gger|faggot|fag\b|d[y1i]ke', friend]
  - ['f+u+c+k+', meecrob]
  - ['\bcrap+|bul+sh[i1]t|s+h+[i1]+t+', poop]
  - ['boobs|t[i1]ts', ears]
  - ['pen[i1]s|d[i1]ck|cock|d[1i]ldo|test[i1]cle|pr[i1]ck|boner', weewee]
  - ['cun+[i1]l+[i1]ng[ue]s|masturbate?', rosieodonnel]
  - ['\bass\b', donkey]
  - ['cunt\b|pus+y|vagina|twat|pus+[i1]es|cunts|cunt|b[i1]tch|labia|clitoris|cl[i1]t|go+ch', puppy]
  - ['anal\b', compulsive]
  - ['bastard', brother]
  - ['orgasm', joke]
  - ['p[o0]rn|\bcum\b|sperm|semen\b|jizz', popcorn]
  - ['pubic', deep]
  - ['blowjob|handjob', reward]
  - ['as+hole|douchebag|douche|slut|whore?', jerk]
  - ['\brape\b|\bddos\b', love]
  - ['piss', pee]
  - ['damn', darn]
  - ['\bsex\b', woohoo]
