ServerName: winthier
ServerDisplayName: Winthier
channels:
  global:
    tag: G
    title: Global
    aliases: [ global, g ]
    description: Cross server chat
  local:
    tag: L
    title: Local
    aliases: [ local, l ]
    description: Local chat
    range: 500
  pm:
    tag: PM
    title: Private
    aliases: [ pm, tell, msg, w]
    description: Private messages
settings:
- channel: global
  key: SenderColor
  value: gray
- channel: global
  key: BracketType
  value: brackets
- channel: global
  key: ChannelColor
  value: white

- channel: local
  key: ChannelColor
  value: dark_aqua
- channel: local
  key: TextColor
  value: dark_aqua
- channel: local
  key: BracketType
  value: paren
- channel: local
  key: ShowServer
  value: 0

- channel: pm
  key: ChannelColor
  value: dark_purple
- channel: pm
  key: TextColor
  value: dark_purple
- channel: pm
  key: SenderColor
  value: dark_purple
- channel: pm
  key: BracketType
  value: angle
patterns:
  URL:
  - ['\b(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.-]*)*\/?\b', website]
  Spam:
  - ['!!+', '!']
  - ['\?\?+', '?']
  Language:
  - ['n[1i]gga|n[1i]gger|faggot|fag\b|d[y1i]ke', friend]
  - ['f+u+c+k+', meecrob]
  - ['\bcrap+|bul+sh[i1]t|s+h+[i1]+t+', poop]
  - ['boobs|t[i1]ts', ears]
  - ['pen[i1]s|d[i1]ck|cock|d[1i]ldo|test[i1]cle|pr[i1]ck|boner', weewee]
  - ['cun+[i1]l+[i1]ng[ue]s|masturbate?', rosieodonnel]
  - ['\bass\b', donkey]
  - ['cunt\b|pus+y|vagina|twat|pus+[i1]es|cunts|cunt|b[i1]tch|labia|clitoris|cl[i1]t|go+ch', puppy]
  - ['anal\b', compulsive]
  - ['bastard', brother]
  - ['orgasm', joke]
  - ['p[o0]rn|\bcum\b|sperm|semen\b|jizz', popcorn]
  - ['pubic', deep]
  - ['blowjob|handjob', reward]
  - ['as+hole|douchebag|douche|slut|whore?', jerk]
  - ['\brape\b|\bddos\b', love]
  - ['piss', pee]
  - ['damn', darn]
  - ['\bsex\b', woohoo]
