main: com.winthier.chat.ChatPlugin
name: Chat

version: 0.1
api-version: 1.19

description: Cross server chat plugin for Cavetale
author: StarTux
website: https://cavetale.com

depend: [Core, Mytems, SQL, Title, Perm]
softdepend: [dynmap]

commands:

  chat:
    aliases: [ ch ]
    description: Command interface
    permission: chat.chat

  join:
    description: Join a channel
    permission: chat.chat
  leave:
    description: Leave a channel
    permission: chat.chat

  ignore:
    description: Ignore someone
    permission: chat.chat

  chatadmin:
    aliases: [ chadmin, chadm ]
    description: Admin interface
    permission: chat.admin

  tell:
    aliases: [msg, pm, whisper, w]
    permission: chat.pm
  reply:
    aliases: [ r, reply ]
    permission: chat.pm

  party:
    permission: chat.channel.party
  p:
    permission: chat.channel.party

  team:
    aliases: [teammsg, t]
    description: Team channel
    permission: chat.channel.team

permissions:

  chat.chat:
    description: Use /chat
    default: op
  chat.admin:
    description: Use /chatadmin
    default: op

  chat.joinmessage:
    description: Display join and leave messages
    default: false
  chat.invisible:
    description: Do not count for the local chat warning while invisible
    default: false

  chat.url:
    description: Pose clickable links in chat
    default: op

  chat.color:
    description: Use legacy color codes
    default: op

  chat.format:
    description: Use legacy formatting codes
    default: op

  chat.unicode:
    description: Use any unicode character
    default: op

  chat.obfuscate:
    description: Use legacy magic code
    default: op

  chat.item:
    description: Paste items in chat
    default: op

  chat.caps:
    description: Override the all-caps check
    default: op

  chat.emoji:
    description: Use emoji
    default: op

  chat.channel.*:
    default: false
    description: Access any channel

  chat.channel.party:
    default: false
    description: Use the party channel

  chat.pm:
    description: Send and receive private messages
    default: op

  chat.channel.team:
    default: false
    description: Use team channel